### ISSUE TITLE
Question : Can this be used to simply watch scroll position ?

### ISSUE THREAD

**Issue by uzumakinaruto123** [Nolanus/ng2-page-scroll#12]
Can this be used to simply watch scroll position ? After certain offset from top of page say 100 i want tochange some css properties . 

If user scrolls back below 100 again then i again need to reverse/change css properties.

Thanks !

**Comment by Nolanus** [comment]
Hi,

no, this library can not be used for that purpose. What you are looking for is related to "scroll spying" like https://www.npmjs.com/package/ng2-scrollspy.

**Comment by uzumakinaruto123** [comment]
Thanks ! ya i got that but its not working . i get the issue i posted here https://github.com/JonnyBGod/ng2-scrollspy/issues/26 

well that feature can be a good addon to this to use. all in one including scrolls to anchor tag.
