### ISSUE TITLE
page scroll Instance error

### ISSUE THREAD

**Issue by CodeCare** [Nolanus/ng2-page-scroll#122]
I am having a problem when I call a pageScrollInstance.
while the method simpleInstance is working perfect, but I want to add the parameters:  pageScrollDuration & pageScrollInterruptible.
So I tried both methods: advancedInstance & newInstance.
**In the case of newInstance the console shows me the error message: "newInstance is not a function".
Here is the code for new Instance:

`import {Component, Input} from '@angular/core';
import {Project} from "../project.model";
import {ProjectsComponent} from "../projects.component";
import {Router,ActivatedRoute} from '@angular/router';
import {PageScrollInstance} from 'ng2-page-scroll';
import {PageScrollService} from 'ng2-page-scroll';

@Component({
  selector: 'project-list',
  styleUrls: ['./project-list.style.scss'],
  templateUrl: './project-list.template.html',
  directives: [ProjectsComponent]
})
export class ProjectListComponent {
	constructor(router: Router, private pageScrollService: PageScrollService)
	{
    this.router = router;
	}
    ngOnInit(){
    console.log("this is project list component");
  }

  clicked(event)
  {
	let pageScrollInstance: PageScrollInstance = PageScrollInstance.newInstance({document: window.document, scrollTarget: '#bottom', pageScrollInterruptible: false, pageScrollDuration: 4000});
	this.pageScrollService.start(pageScrollInstance);
  }
    parentHandlingFcn(receivedParam: string)
	{
    	console.log("this executes third, with " + receivedParam); //string from child
	}
    @Input() projects: Array<Project>;
}
`

**In the case of advancedInstance the console shows me the error message "document.body is undefined".
Here is the code for advanced Inastance:

`import {Component, Input} from '@angular/core';
import {Project} from "../project.model";
import {ProjectsComponent} from "../projects.component";
import {Router,ActivatedRoute} from '@angular/router';
import {PageScrollInstance} from 'ng2-page-scroll';
import {PageScrollService} from 'ng2-page-scroll';

@Component({
  selector: 'project-list',
  styleUrls: ['./project-list.style.scss'],
  templateUrl: './project-list.template.html',
  directives: [ProjectsComponent]
})
export class ProjectListComponent {
	constructor(router: Router, private pageScrollService: PageScrollService)
	{
    this.router = router;
	}
    ngOnInit(){
    console.log("this is project list component");
  }

  clicked(event)
  {
	let pageScrollInstance: PageScrollInstance = PageScrollInstance.advancedInstance({document: window.document, scrollTarget: '#bottom', pageScrollInterruptible: false, pageScrollDuration: 4000});
	this.pageScrollService.start(pageScrollInstance);
  }
    parentHandlingFcn(receivedParam: string)
	{
    	console.log("this executes third, with " + receivedParam); //string from child
	}
    @Input() projects: Array<Project>;
}
`

**Comment by Nolanus** [comment]
`advancedInstance` is still present in the library but marked as deprecated. It will be removed in a later release. The signature of `advancedInstance` does not take an object but multiple single arguments.

Please make sure you've got the latest release installed and all caches cleared, as `PageScrollInstance.newInstance` was added in the latest release.

**Comment by CodeCare** [comment]
I have cleared the caches and upgraded ng2-page-scroll to 4.0.0-beta.6
I still have the same message:
"EXCEPTION: ng2_page_scroll_1.PageScrollInstance.newInstance is not a function"
"TypeError: ng2_page_scroll_1.PageScrollInstance.newInstance is not a function"

**Comment by mclr47** [comment]
PageScrollInstance.**newInstance**
   the newInstance method missing or some other error detected on VSCode.

Specific error from VSCode:
"Property 'newInstance' does not exist on type 'typeof PageScrollInstance'.ts(2339)"
