### ISSUE TITLE
Update router to 3.0.0-alpha.7

### ISSUE THREAD

**Issue by adriancarriger** [Nolanus/ng2-page-scroll#13]
Angular's new 3.0 router has breaking changes for subscribing to route changes. I created a [fork](https://github.com/adriancarriger/ng2-page-scroll/tree/update-router-and-angular) to work with my project, and would be happy to submit a PR if it would help.

**Comment by Nolanus** [comment]
Hi Adrian,
yes, please create a pull request. I will then check the changes and merge your commit.

Thanks
