### ISSUE TITLE
Is it possible to have the menu items become active automatically on scroll?

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [Nolanus/ng2-page-scroll#134]
While I'm scrolling the page, I'd like to highlight my menu items automatically, so that user understand where he/she is in the navigation. I haven't seen something in the documentation like this. Is this possible or can I add it myself?

**Comment by Nolanus** [comment]
Hi,
no it's not: https://github.com/Nolanus/ng2-page-scroll/wiki/FAQ#is-it-possible-to-detect-the-current-scroll-section

**Comment by tobi-or-not-tobi** [comment]
Thanks @Nolanus
