### ISSUE TITLE
Page focus does not change to scrolled to anchor.

### ISSUE THREAD

**Issue by kevfuzz** [Nolanus/ng2-page-scroll#142]
Hi,

Is there any way to have the page focus move to the scrolled to anchor?

Thanks,
Kevin.

**Comment by Nolanus** [comment]
Hi Kevin,

You could register a `pageScrollFinish` listener and manually focus the scrollTo element in there. There's no build-in way of doing that at the moment.

**Comment by kevfuzz** [comment]
Thanks for the update.
