### ISSUE TITLE
No Scroll Animation When Scrolling Upwards

### ISSUE THREAD

**Issue by phoenixdesignza** [Nolanus/ng2-page-scroll#170]
When using directive scrolling, all scrolls are animated when scrolling down a page. When trying to scroll back up, there are no animations and it just jumps back up to the element.

For example, in [this code snippet,](https://gist.github.com/phoenixdesignza/1b325fb1cf835b018a2e72b3d9e10ba3) when clicking on the contact us link, the scroll animates to the contact section. Then when clicking on the home link, it jumps back to the home section instead of animating.

**Comment by phoenixdesignza** [comment]
Thanks for the quick fix @Nolanus. When will the update be reflected in the npm package?

**Comment by Nolanus** [comment]
The npm package just got updated a few minutes ago (beta.9 release).

**Comment by phoenixdesignza** [comment]
Thanks a ton!
