### ISSUE TITLE
Scroll across routes

### ISSUE THREAD

**Issue by TiagoSilvestre** [Nolanus/ng2-page-scroll#185]
How can I do this?

- works across routes (scrolls to target element as soon as the routing has finished) and in both directions (horizontal/vertical)

I have a header with links but when the page its not in home and the user click in a link, the scroll doesnt work.

Thanks!

**Comment by Nolanus** [comment]
Hi. Scrolling across routes currently only works if the "target" is not dynamically added/manipulated (e.g. using a ngFor loop). This is a known bug I have to work on and was introduced by a change in recent angular update.

Check the demo app and especially the two buttons on the "Home" Tab: https://nolanus.github.io/ng2-page-scroll/

**Comment by TiagoSilvestre** [comment]
I cant understand how to scroll after the url change. For example: 

Im doing a website, it has a header, in some links in the header, have to make the scroll effect, 
but the problem is when the components changes 

The example links is this website: https://ridestate.com/

**Comment by Nolanus** [comment]
The Usage section of the Readme explains how to use the scroll functionality: https://github.com/Nolanus/ng2-page-scroll#usage
Either use the `pageScroll` directive for convenience or use the `PageScrollService` to trigger whenever you want the scroll animation to take place.
