### ISSUE TITLE
Not working fine with Angular 2 + Material Design 

### ISSUE THREAD

**Issue by vikasparashar02** [Nolanus/ng2-page-scroll#191]
I have used "ng2-page-scroll" plugin in angular 2 + bootstrap, it is working fine. But whenever i have used this plugin in Angular 2 + material design then we faced below error.  

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

Please help me how to resolve this issue. I am waiting for your response.

Thanks in advance.

**Comment by Nolanus** [comment]
Hi @vikasparashar02,

does this prevent your angular app form working as expected?

Passive-event listeners and angular are not ready yet (see https://github.com/angular/angular.js/issues/15901), so I fear there's no immediate way to resolve that.

As a workaround you may remove the "wheel" event from the list events that will cancel an ongoing scroll-animation (https://github.com/Nolanus/ng2-page-scroll/blob/master/src/ng2-page-scroll-config.ts). Something like the following (untested) code should do it:

```
let wheelEventPos = PageScrollConfig._interruptEvents.indexOf('wheel');
if (wheelEventPos > -1) {
    PageScrollConfig._interruptEvents.splice(wheelEventPos, 1);
}
```

**Comment by vikasparashar02** [comment]
Hi @Nolanus,

Yes it working as per my accepted in angular 2 + bootstrap application. Whenever we migrate this app Angular 2 + Material design then I faced this issue.

As per your suggestion, I pasted this code into ng2-page-scroll-config.js then I faced another issue like-

[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

I resolved this issue form below code-

let mouseWheelEventPos = PageScrollConfig._interruptEvents.indexOf('mousewheel');
if (mouseWheelEventPos > -1) {
    PageScrollConfig._interruptEvents.splice(mouseWheelEventPos, 1);
}

Bad thing here, scroll is not working.  I have attached sample code. You just download, and run npm install and at last run ng serve. 
When application is run, then in home page have a click button "Back To Top". If user click on this button then scroll should be go on top. 


[vikas.zip](https://github.com/Nolanus/ng2-page-scroll/files/1181975/vikas.zip)

Please help me to resolve this issue. Thanks in advance.

Regards,
Vikas Parashar

**Comment by Nolanus** [comment]
Please create a plunkr/jsfiddle showcasing your problem.
Is there any warning/error in the console? Double check that the target element (e.g. `<div id="top">`) is present on the page and the your using the correct scrolling view (https://github.com/Nolanus/ng2-page-scroll/wiki/Using-the-right-scrolling-view).
