### ISSUE TITLE
How to add active class to the navbar based on the scroll position?

### ISSUE THREAD

**Issue by rahuldpi** [Nolanus/ng2-page-scroll#195]
I would like to highlight the active section in the menu. Similar to this: 
[https://v4-alpha.getbootstrap.com/components/scrollspy/](https://v4-alpha.getbootstrap.com/components/scrollspy/)

Does ng2-page-scroll plugin provides such functionality natively or are there are Angular based plugins available to implement such functionality? I'm using bootstrap 4 framework with latest version of Angular.

**Comment by arun-awnics** [comment]
Your requirement seems like you need to go to a certain section in a page. I don't think that should be a tough job for you. You may implement the same by giving the id attribute to the specific section of the page.

```
<a pageScroll href="#header">Section</a>
<h2 id="header">Section header</h2>
```

**Comment by rahuldpi** [comment]
Hi arun-awnics, 

I think you didn't get my question correctly. The example which you provided is the core functionality of the ng2-page-scroll plugin. I need the visible section to bind with the navigation menu.

Eg: If user is currently on section 2. Then in the navbar it should append an active class which I can style it.

**Comment by arun-awnics** [comment]
Hi @rahuldpi 

Can you kindly create a plunker for the issue you are facing? I don't see much difficulty here. Just adding ```pageScroll``` should have worked. But may be there is a work around for that.

**Comment by Nolanus** [comment]
Hi. Please refer to https://github.com/Nolanus/ng2-page-scroll/wiki/FAQ#is-it-possible-to-detect-the-current-scroll-section and maybe take a look at old tickets using the search ;) (#167, #163, #134)
