### ISSUE TITLE
PageScroll not working when the element inside router outlet

### ISSUE THREAD

**Issue by Nolanus** [Nolanus/ng2-page-scroll#2]

**Comment by bbottema** [comment]
Yep, same here. It's not working from a view loaded by the router.

**Comment by bbottema** [comment]
Correction. It doesn't work with the beta router ("router-deprecated"), but it does work after upgrading my app to the new rc1 "router".

**Comment by luckymark** [comment]
I use the new rc1 "router",but I got some error like this:
node_modules/ng2-page-scroll/src/ng2-page-scroll.directive.ts
(30,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
