### ISSUE TITLE
(SystemJS) Can't resolve all parameters

### ISSUE THREAD

**Issue by pgreaney** [Nolanus/ng2-page-scroll#204]
This just started happening recently, but I'm now receiving 

"Error: (SystemJS) Can't resolve all parameters for PageScroll: ([object Object], [object Object], ?).
	Error: Can't resolve all parameters for PageScroll: ([object Object], [object Object], ?)."

This occurs on page load as the PageScrollModule is being loaded in the app module.

I'm using the PageScrollService in my components by importing the service, config, and instance, and setting it up just like the documentation says.

Has anyone run into this and if so, found a solution?

**Comment by Nolanus** [comment]
The lower bound of the angular version-constraint was too low. Version 4.2.6 or greater is required.

**Comment by pgreaney** [comment]
Alright, I've updated; now when I go to use the service I get it telling me 

"Failed to execute 'querySelector' on 'Document': '#1501912800' is not a valid selector." the ID of the element I want to scroll to matches that ID, but it doesn't scroll and spits this out.

**Comment by Nolanus** [comment]
The `querySelector` method takes a css-selector. For css selectors it is not allowed to have an id-selector starting with a number.
You could either adjust your ids or use one of the suggested workarounds from https://css-tricks.com/ids-cannot-start-with-a-number/

**Comment by pgreaney** [comment]
Alright, I'll add a string in front first, see if that helps. thanks for the quick response!

**Comment by manu2504** [comment]
I tried to update to angular 4.2.6 this way (in my project's root folder):
`npm install @angular/core@4.2.6`
`npm install @angular/common@4.2.6`
But afterwards I get:
`+-- UNMET PEER DEPENDENCY @angular/common@4.1.3`
`+-- UNMET PEER DEPENDENCY @angular/core@4.1.3`
(This angular version being required by other plugins of my Ionic project)
How should I do please?

**Comment by Nolanus** [comment]
All angular dependencies need to have the same version number. You may try to update your ionic plugins to a newer version supporting 4.2.X if available or use ng2-page-scroll version 4.0.0-beta.10

**Comment by manu2504** [comment]
Thank you but whatever I do, I still have (apparently) ng2-page-scroll@4.0.0-beta.11: the command `npm view ng2-page-scroll version` returns indeed `4.0.0-beta.11`, even after running `npm uninstall ng2-page-scroll --save`...

**Comment by Nolanus** [comment]
Try removing the `node_modules` and run `npm install` again.

**Comment by manu2504** [comment]
That's what I did but I get: `npm ERR! peer dep missing: @angular/common@>=4.2.0 <5.0.0, required by ng2-page-scroll@4.0.0-beta.10`
My Ionic version seems to be up-to-date:
![screenshot 2017-08-15 23 09 32](https://user-images.githubusercontent.com/25584381/29336706-f8759c80-820e-11e7-8d58-4f4018a29d6b.png)

**Comment by Nolanus** [comment]
Hi,
I'm sorry, as written in the [Change Log](https://github.com/Nolanus/ng2-page-scroll/blob/master/CHANGELOG.md), version 4.0.0-beta.10 raised the lower version limit to 4.2.0. Please try beta.9, that one has `>=2.4.0 <5.0.0` as angular version constraint.
