### ISSUE TITLE
PageScrollConfig._logLevel = 0 does not turn off all debugmessages in console

### ISSUE THREAD

**Issue by moritz439** [Nolanus/ng2-page-scroll#207]
When using ng2-page-scroll as a service and `PageScrollConfig._logLevel = 0` it will still output 
"`Scrolling not possible, as we can't get any closer to the destination`" to console.

**Comment by Nolanus** [comment]
Hi @moritz439. These messages are always printed when being in devMode, so when angular is not put into production mode. After building your application nothing should be logged.

I agree that this is a little confusing and not clearly separated or documented somewhere. I'll therefore leave this ticket open to address this.

**Comment by moritz439** [comment]
Thank your for the quick reply and nice work!
