### ISSUE TITLE
Cannot scroll divs with scrollbars

### ISSUE THREAD

**Issue by davidTurczi** [Nolanus/ng2-page-scroll#21]
Since the "scrollToTopSources" is hardcoded to body/document related stuff, I cannot make it scroll a div.

**Comment by Nolanus** [comment]
Support added for version 2

**Comment by AdrianMrn** [comment]
What method should I use to scroll in a scrolled div instead of in the document? Can't seem to find it.

**Comment by Nolanus** [comment]
Use the PageScrollService (example from Readme):

```
     public goToHeadingInContainer(): void {
         let pageScrollInstance: PageScrollInstance = PageScrollInstance.newInstance({document: this.document, scrollTarget: '.headingClass', scrollingViews: [this.container.nativeElement]});
         this.pageScrollService.start(pageScrollInstance);
     };
```

Running examples can be found in the [demo app](https://nolanus.github.io/ng2-page-scroll/) after clicking "Nested Scrolling"

**Comment by AdrianMrn** [comment]
Thanks for the super fast answer! This worked!

One more question (or should I create a new issue for this?):
The scroll doesn't seem to work if I try scrolling to an item id that was added after the page loaded.

**Comment by Nolanus** [comment]
Scrolling to any element should work as long as it exists when the scroll animation starts. It's not necessary that the target element exists on page load.

**Comment by AdrianMrn** [comment]
You're correct. It seems like I'm having issues with my Observable, I can't seem to call the scroll function when the Observable has finished running.
