### ISSUE TITLE
Can't resolve all parameters for PageScroll

### ISSUE THREAD

**Issue by manu2504** [Nolanus/ng2-page-scroll#213]
Hello. Since I added this module into my project, I get this runtime error message: "Can't resolve all parameters for PageScroll: ([object Object], [object Object], ?)."
How shall I fix this?

Here is how I use the pageScroll directive in my (Ionic) project:
`<button pageScroll href="#section-4">`

I use angular 4.1.3 and Node 7.7.3.
I am testing the functionality in Firefox 54.0.1 (64bits)

I added this package to the root injector of my app as suggested:
`import {Ng2PageScrollModule} from 'ng2-page-scroll';`
with
`imports: [
    ...,
    Ng2PageScrollModule
  ]`

**Comment by Nolanus** [comment]
Hi @manu2504,

you seem to get the same error message like #204.
Please note that starting with version 4.0.0-beta.11 the library requires angular 4.2.6 or later.
