### ISSUE TITLE
Does not scroll to translated elements

### ISSUE THREAD

**Issue by mihaivarga** [Nolanus/ng2-page-scroll#22]
It does not scroll to elements that are translated in css. For this elements using offsetTop is not a good solution. 

Possible solution:
http://stackoverflow.com/questions/22268265/how-to-get-the-element-position-after-css-translation

**Comment by Nolanus** [comment]
Please check out the latest release version 3.0 which supports scrolling to transformed DOM elements.
An example has been added to the demo application as well.
