### ISSUE TITLE
Easing Logic Usage

### ISSUE THREAD

**Issue by ArpitaCkb** [Nolanus/ng2-page-scroll#220]
Hi,

The scroll funtion works perfectly with app, but I can't find more description on the usage of defaultEasingLogic and pageScrollEasing. Are there more values other than linearEasing? 

You have used a method in the readme doc and demo application for the pageScrollEasing. Do we have to write such methods for different types of easing transitions?

Thanks,
Arpita

**Comment by Nolanus** [comment]
Hi @ArpitaCkb,
the only "included" easing is the linear one. For custom easing you have to get a easing method and set the respective value, either per scroll-action or for all scroll-actions using the `defaultEasing` value. An example of the latter one may be found at https://github.com/Nolanus/ng2-page-scroll#example.

You may find easing methods for example at http://gizma.com/easing.

**Comment by ArpitaCkb** [comment]
Thank You :)
