### ISSUE TITLE
n2-page-scroll not scrolling properly

### ISSUE THREAD

**Issue by dpstart** [Nolanus/ng2-page-scroll#229]
I'm trying to scroll to a certain element on my template, but the page scrolls instead to another point (above the expected destination).

Here's the trigger:

```
goToAreYouReady(): void {
    let pageScrollInstance: PageScrollInstance = PageScrollInstance.simpleInstance(this.document, '#areyouready');
    this.pageScrollService.start(pageScrollInstance);
  }
```

I'm thinking that maybe it could be because the trigger element and the destination are in different templates...
Any solution?

**Comment by Nolanus** [comment]
Hi.
Unfortunately based on your provided information it's not possible to tell what causes the problem. Maybe you can create a plnkr showcasing the issue. It's probably related to the styling of your page.
