### ISSUE TITLE
Scroll past element

### ISSUE THREAD

**Issue by Fauxry** [Nolanus/ng2-page-scroll#236]
I'm having problems with the scroll, it goes past the top of the element.

For example, setting a target id at the start(heading) of table row or a div , it will scroll to the middle of the row instead of the point where the selector is present.

I know I could use offset but that wouldnt work well with responsiveness and thats quite important.

**Comment by Nolanus** [comment]
Hi @Fauxry,

it is probably related to some css styling. Could you please provide details about how you trigger the scroll (directive or service), what additional properties are (inline, duration/speed, ...) and create a plnkr (you may use [this plnkr](http://plnkr.co/edit/arVC6zldzxR3xZGze9yo?p=preview) as a starting point).

**Comment by Fauxry** [comment]
Hey Nolanus, thanks for the reply
I dont really have time to create a plnkr at the moment but if you really need one after this, i'll try to.

I've taken screenshots of my problem:

Below is the selector which i use to trigger the click event. clicking the image will make the page scroll down to the table row.
![icon href](https://user-images.githubusercontent.com/26525146/31809010-109d0254-b576-11e7-9a6f-6db0d63397e6.PNG)

The target element:
![target](https://user-images.githubusercontent.com/26525146/31809058-402af56c-b576-11e7-98b1-94a7d4819970.PNG)

When I click the icon, the top of the setup table row is what i expect it to scroll to.
![target web expected](https://user-images.githubusercontent.com/26525146/31809103-6b2a4196-b576-11e7-87bc-e914f2609485.PNG)

However, it instead scrolls to the halfway point of the row:
![target web result](https://user-images.githubusercontent.com/26525146/31809116-7d0ce71a-b576-11e7-910f-a746fab14c70.PNG)

Like I said, if you really need a plnkr, ill get to it but i hope this is enough to explain the problem.

Thank you.

**Comment by Nolanus** [comment]
Hi,
as assumed it's not a general issue of using a `<tr>` as scroll target. See [this working example](http://plnkr.co/edit/1XacY7?p=preview) which is based on your provided code.

**Comment by Fauxry** [comment]
Im using SASS, could this be a reason? ive tried the scrolling on normal divs with no styling, still goes past it

**Comment by Fauxry** [comment]
Hello, 
Turns out it's a pretty trivial reason why this is happening. We have a navigation bar that stays fixed on top of the page hence why the scrolling looks like it goes past the element.
