### ISSUE TITLE
Is there a way to pageScroll without <a href=  , manually trigger on the script side?

### ISSUE THREAD

**Issue by subatomicglue** [Nolanus/ng2-page-scroll#27]
We have several places in our project which jump using the `router.navigate` method called by `(click)` event from html.   No `<a href=""` is used in our html.  When I set the `fragment` input parameter to `router.navigate`, the pagescroll does not jump.

Looking at the members of `PageScroll` doesn't seem clear to me what I would call to trigger a jump from script side.

New urls input in the browser `http://myhost/route#anchor1` just reloads the page, and does not scroll... but that seems expected or otherwise you wouldn't need `pageScroll` on every `a href` tag.   To enable this feature, I suppose in `ngOnInit()` you could `route.params.subscribe` and then read the `router.routerState.fragment` and then manually call the appropriate `PageScroll` method to scroll the page...  if such a method exists. :)

**Comment by mhov** [comment]
Funny I came here to ask the same question.  I need to scroll from the code as a result of a REST call.

**Comment by Nolanus** [comment]
Hi. Thanks for sharing your experience. Triggering a scroll from (java/type)script currently is not possible, but will be once I tackled #16. Unfortunately I don't have spare time in the upcoming days, so I can't give any estimate when this will come

**Comment by Nolanus** [comment]
Service implementation added in version 2.0
