### ISSUE TITLE
IEasingFunction not found on angular-cli (webpack with RC5)

### ISSUE THREAD

**Issue by lcamargof** [Nolanus/ng2-page-scroll#28]
I just installed the directive with "npm install ng2-page-scroll --save", I imported the "PageScroll" to my app.module.ts file without a problem, when the chrome developer tools it says:

_./~/ng2-page-scroll/src/ng2-page-scroll.directive.ts
161:55 export 'IEasingFunction' was not found in './ng2-page-scroll-config'
Error: export 'IEasingFunction' was not found in './ng2-page-scroll-config'_

It's very strange because I checked your files and everything is in order, the ng2-page-scroll-config exports correctly the interface, but still, it isn't working, maybe it's not compatible with the angular-cli webpack version?

**Comment by pcwa-ahendricks** [comment]
I'm having the same issue after upgrading to angular-cli@webpack.  There was no error when using angular-cli with System.js.

**Comment by Nolanus** [comment]
Please see the new demo app and the latest release 3.0.0
