### ISSUE TITLE
Where has defaultEasingFunction gone?

### ISSUE THREAD

**Issue by cortopy** [Nolanus/ng2-page-scroll#31]
I just upgraded to v3. It works great with rc6. However, typescript started complaining that:

```
Property 'defaultEasingFunction' does not exist on type 'typeof PageScrollConfig'.
```

I've looked into the src config file and indeed, there doesn't seem to be a a defaultEasingFunction config class property. The README still mentions it though

**Comment by Nolanus** [comment]
Hi,

looks like I definitely overlooked that one. It has been renamed to defaultEasingLogic, as the object type has changed as well.

I just updated the Readme

**Comment by cortopy** [comment]
Thank you @Nolanus !! So quick!! Working like a charm
