### ISSUE TITLE
i can't run the demo

### ISSUE THREAD

**Issue by zamboney** [Nolanus/ng2-page-scroll#33]
when i `npm run demo` and `npm install` it's throw me an error 
[npm-debug.txt](https://github.com/Nolanus/ng2-page-scroll/files/466733/npm-debug.txt)

**Comment by Nolanus** [comment]
Hi,

thanks for the report. Unfortunately I'm not sure what's exactly causing the installation to fail. Can you please retry with the latest release. If this does not solve it, could you try running the commands the `npm run demo` performs (as described [in the Readme](https://github.com/Nolanus/ng2-page-scroll#example-app)) manually to narrow down which if them fails.

Regards
Sebastian

**Comment by dantesguilherme** [comment]
I had the same issue.

```
Running:
- node v4.50 
- npm 3.10.7
```
it fails on _"npm run compile"_ at the main project.

**to solve the demo app** you have to change the _package.json_ from:
```
"ng2-page-scroll": "file:../",
```
to:
```
"ng2-page-scroll": "3.1.0",
```
