### ISSUE TITLE
Compatibility with Angular AOT

### ISSUE THREAD

**Issue by noemi-salaun** [Nolanus/ng2-page-scroll#35]
**Angular version:** 2.0.0

**ng2-page-scroll version:** 3.1.0
## Issue

Erreur when using Ahead-of-Time compilation.

```
Error: Unexpected value 'Ng2PageScrollModule ' imported by the module 'AppModule'
```
## Code

```
import {Ng2PageScrollModule} from 'ng2-page-scroll';

@NgModule({
    imports: [
        /* Other imports here */
        Ng2PageScrollModule
        ]
})
export class AppModule {
}
```

Then use `ngc -p some-tsconfig-aot.json`.
## TODO

You need to add metadata.json files for AOT to understand how your lib works.

*.metadata.json are generated by the Angular compiler (ngc).

See [AOT documentation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)
## Bonus

I just spend the day updating our internal projects for AOT compatibility. I should be able to do the same with your project. I also make the compability with RollupJS.

For ease of the integration of AOT and rollup, and avoid the need to set up projects that will use your lib, it must respect some convention. But I do not want to impose my way of doing to your code 😉

**Comment by egervari** [comment]
Same problem here

**Comment by Nolanus** [comment]
Hi,

I was able to get ngc compiling the sources. Check out the [aot-support branch](https://github.com/Nolanus/ng2-page-scroll/tree/aot-support). Unfortunately I get an error with the "Document" type (`Could not resolve type Document (position 46:123 in the original .ts file), resolving symbol PageScroll in ng2-page-scroll/src/ng2-page-scroll.directive.ts`) and I didn't manage to wrap my head around how to include the json's and ngfactories in the library build...
Appreciating your hints for that!

Sebastian

**Comment by noemi-salaun** [comment]
AoT does not handle `Document` type on injection. When I met such case, I checked on [Angular source code](https://github.com/angular/angular/blob/b5d14c26d25c4f60b89681d4d88f4f081b0828e8/modules/%40angular/platform-browser/src/dom/dom_renderer.ts#L63) to see how they handle it, and found out that they use type `any`.

**Comment by noemi-salaun** [comment]
As your project is a library, you don't have to generate factories, just metadata. The application that is goind to use your library will generate factories itself, based on your metadata.

In your **tsconfig-aot.json**, set `skipMetadataEmit` to false and `skipTemplateCodegen` to true.

```
"angularCompilerOptions": {
    "genDir": "aot",
    "debug": true,
    "skipMetadataEmit": false,
    "skipTemplateCodegen": true
}
```

You can look at my [project ](https://github.com/noemi-salaun/ng2-logger) if you want to see how I'm doing it.

**Comment by sebastian-heinz** [comment]
Hello i encountered an issue:

`Error encountered resolving symbol values statically. Could not resolve type  Window (position 11:39 in the original .ts file), resolving symbol`

the window is from lib.d.ts as far as i can tell, this is my tsconfig

```
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
```


this is the relevant part from my .ts file

```
@Injectable()
export class SwService {

  private window: Window;

  constructor(@Inject(Window) window: Window) {
    this.window = window;
```

if i change window to any it works

```   constructor(@Inject(Window) window: any) { ```

Any ideas why Window cannot be statically analyzed?

**Comment by bmurali31** [comment]
Could  you please change the Document type in the injection to "any" as @noemi-salaun mentioned?  
At least it'll help us to proceed with our project compilation.

**Comment by Nolanus** [comment]
@bmurali31, please check out the latest release 3.1.2

**Comment by bmurali31** [comment]
Thank you @Nolanus it works like a charm.

**Comment by inzerceubytovani** [comment]
I confirm that, this works perfectly.
