### ISSUE TITLE
It doesn't work as expected in Google Chrome

### ISSUE THREAD

**Issue by pablolazaro** [Nolanus/ng2-page-scroll#37]
Hi @Nolanus, first of all, thank you for your time and for bringing to us this library.

Have you noticed an strange behaviour in the last versions of Google Chrome?

I'm trying to use your library in a project of mine and I can't achieve to make it work properly in Google Chrome. I also tried your demo with the same result.

The problem is that the scroll does not move correctly to the element.

I'm using `Google Chrome Versión 53.0.2785.143 m (64-bit)`.

It works perfectly in `Firefox Developer Edition 51.0a2 (2016-10-03) 32-bit` and `Internet Explorer 11 11.0.9600.18450`.

![](http://i.giphy.com/l0HlJFGasQgKeabx6.gif)

**Comment by Nolanus** [comment]
Hi,

thanks for reporting your problem. Unfortunately I'm not able to reproduce it. Tried the mentioned Chrome version in OS X and Windows 7, both work as expected.
Are there any errors or logs on the console?

**Comment by tobwiens** [comment]
I have the same problem, it appears since the update to 2.0.0 final. 

No logs/errors inside the browser.

**Comment by LeiwenL** [comment]
:+1: Same problem ! :disappointed:

**Comment by rgrasso** [comment]
Same problem. I am on Windows 10 64bit, no errors, works in Firefox and worked in Chrome until Chrome update (now on Version 53.0.2785.143 m). Also works fine in android versions of both Firefox and Chrome.

**Comment by mwijnands** [comment]
The key is High-DPI screens. For me in Chrome is doesn't work on a 4K screen, but is does work on a 1080p screen. It works correctly in the other desktop browsers.

I don't know why, but it's true.

**Comment by Invis1ble** [comment]
I can confirm issue in Chromium (53.0.2785.143 Built on Ubuntu, running on Ubuntu 16.04 (64-bit)).
In firefox it works as expected.
I'm using `3.2.1` version.
There is no any errors in the console.

**Comment by LanderBeeuwsaert** [comment]
Jep,
same here,
3 screens of 2560 x 1440 (so that is below 4K I think).
Works on firefox and edge.

Does not work on chrome 54.
There seems to be exactly one 'jump' or 'frame' which is executed, after that, none anymore...

**Comment by Darkroll76** [comment]
Hi, 

I have exactly the same issue on chrome. Did someone find how to fix it ? 
Or we just have to wait for an update of the module or chrome ?

Thanks

**Comment by Nolanus** [comment]
I'll try to test the scrolling on a high dpi screen using chrome, however I assume it is a problem in the browser, as it works in the others (or chrome is even more strict and stays to the rules, whereas all others apply some "compatibility" logic?!).

**Comment by Invis1ble** [comment]
@Nolanus I don't think that the issue in the hight DPI. I have old display https://www.amazon.co.uk/Acer-V223HQ-21-5-Widescreen-Monitor/dp/B001GH1QAE#productDetails

**Comment by Nolanus** [comment]
@Invis1ble, thanks for the feedback. Sorry for asking again, but may you try http://nolanus.github.io/ng2-page-scroll/ with Windows 10 and latest Chrome (54.0.2840)? Does it work in "Incognito Mode" without any AddOns? Do you have english locale?

**Comment by LanderBeeuwsaert** [comment]
I have tried:
with Windows 10 and latest Chrome (54.0.2840.87)
with and without incognito mode: Both work.
nl_be locale I think.
If I try my code: dev version of https://github.com/AngularClass/angular2-webpack-starter/pulse then it does not work.

**Comment by Invis1ble** [comment]
@Nolanus Sorry, I can't test it on Windows. Also, the demo works fine in Chrome. I'll try to debug my case later. Maybe the reason in the url's anchor (#some-anchor) that I change before scrolling.

**Comment by Invis1ble** [comment]
I've just updated to `v3.2.3` (from `v3.2.1`) and it fix my issue.

**Comment by LanderBeeuwsaert** [comment]
Jep, works as a charm.
