### ISSUE TITLE
Problems within I-Frame

### ISSUE THREAD

**Issue by webia1** [Nolanus/ng2-page-scroll#38]
If you call the app directly, everything works as expected but if an angular2-app is loaded in an I-Frame (currently by OneWebCMS), the scrolling does not work. There is no error message. 

kind rgds

**Comment by Nolanus** [comment]
Hi @webia1,

thanks for your feedback. I tried the following example with the demo app from this repo running at localhost:4200:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<iframe src="http://localhost:4200" width="500px" height="50%" style="margin-left: 250px;"></iframe>
</body>
</html>
```

The scrolling works as expected. Could you please provide some more details on the used iFrame properties and the used scroll-action (using service or directive, page layout etc).

**Comment by webia1** [comment]
I can tell you more approx. on tuesday, would you try it within a tomcat or jboss container? Maybe that is the reason, or the OneWebCMS overwrite something?

**Comment by Nolanus** [comment]
The server platform providing the js/html/... files shouldn't impact the browser-side processing. However it could be that styling or javascript code from the OneWebCMS interferes with the execution of the angular2 application inside the iframe.

**Comment by webia1** [comment]
It is a OneWeb-Issue :/
