### ISSUE TITLE
No provider for Router!

### ISSUE THREAD

**Issue by dolanmiu** [Nolanus/ng2-page-scroll#40]
I'm using version `3.1.2` of `ng2-page-scroll`

I am doing the absolute bare minimum to get it to work, and I can't get it to work, I get the following error:

```
error_handler.js:45EXCEPTION: Error in ./NavComponent class NavComponent - inline template:5:16 
    caused by: No provider for Router!
    ErrorHandler.handleError @ error_handler.js:45
    (anonymous function) @ application_ref.js:209
    ZoneDelegate.invoke @ zone.js:192
    onInvoke @ ng_zone_impl.js:43
    ZoneDelegate.invoke @ zone.js:191
    Zone.run @ zone.js:85
    (anonymous function) @ zone.js:451
    ZoneDelegate.invokeTask @ zone.js:225
    onInvokeTask @ ng_zone_impl.js:34
    ZoneDelegate.invokeTask @ zone.js:224
    Zone.runTask @ zone.js:125
    drainMicroTaskQueue @ zone.js:357

error_handler.js:47ORIGINAL EXCEPTION: No provider for Router!
```

Screenshot here:
![screen shot 2016-10-09 at 03 39 51](https://cloud.githubusercontent.com/assets/2917613/19217422/9ea57dbe-8dd2-11e6-9e75-952b4e923f30.png)

**Comment by Nolanus** [comment]
Hello @dolanmiu,

according to your screenshot you're trying to run your own application and not the demo application from this repo. The error `No provider for Router!` notifies you that you're injecting the router somewhere without having specified where the router comes from (missing a definition how the router is provided).
Please check out the [official angular2 guide for the router](https://angular.io/docs/ts/latest/guide/router.html) or [this frequently updated stackoverflow question](http://stackoverflow.com/questions/33187235/getting-angular2-error-no-provider-for-router-routeroutlet-router).

**Comment by Nolanus** [comment]
As the `pageScroll` directive has the capability of listening to route changes before starting the scroll animation, it has a dependency on `@angular/router`. If the router is not present you will see this error.

As immediate workaround adding the angular router to your project should fix the problem. I'll have to investigate whether there is a way to make the dependency "weaker", but I fear this is not possible.

**Comment by Kamshak** [comment]
@Nolanus i think you can use the @Optional() Decorator to mark the Dependency optional to the Injector - you should simply get null as router then

**Comment by Nolanus** [comment]
It is now possible to create an angular app without `@angular/router` dependency and use the directive and service to trigger scrolls. Anyhow, this package will remain a peerDependency to inform the package users that not all functionality of ng2PageScroll will be available without the angular router.
