### ISSUE TITLE
ES2015 modules

### ISSUE THREAD

**Issue by ghetolay** [Nolanus/ng2-page-scroll#41]
On the latest 3.1.2 version you are compiling modules as `es2015` instead of `commonjs` modules.

I guess it's a simple mistake.

**Comment by Nolanus** [comment]
Hi @ghetolay,

inside the `/bundles/` you may find umd format modules to be used in commonJs. I just updated the Readme to showcase possible usage of these files.

**Comment by ghetolay** [comment]
Hi,

Thks for your update for systemJS users.
But I was being silly because I'm using webpack and `es2015` modules are fine. I just got an `unexpected token export` error and I assumed things too fast.

Anyway I don't know what was the real cause of that error but latest version seems to fix it. (maybe this was due to `typings` folder being published).

**Comment by macliems** [comment]
Hi ghetolay,

Can you tell me how you to use the scroll with webpack? Just import the module in my app.module or do I have to do additional stuff?

**Comment by ghetolay** [comment]
Yes nothing more to do with version `3.2.1`. Do you have any trouble ?

**Comment by macliems** [comment]
Thanks!!! 
I'm about to try it out. Just looking around for things I'll need. Like scrolling and ways to animate components in and out (if you have a link for the latter, please let me know!).
