### ISSUE TITLE
IDE error

### ISSUE THREAD

**Issue by kiuka** [Nolanus/ng2-page-scroll#47]
Hi,

When I try to import Ng2PageScrollModule, PHPStorm shows an error. It says the file is not in the tsconfig:

![image](https://cloud.githubusercontent.com/assets/11283191/19410925/baef6ba4-92f7-11e6-8dea-d119fb13b250.png)

In ng2-page-scroll.ts:

![image](https://cloud.githubusercontent.com/assets/11283191/19410930/d60d019e-92f7-11e6-9b1d-7ac8e452bd70.png)

The module works fine, but the problem is really annoying. Could you fix it please?

**Comment by Nolanus** [comment]
Hi @kiuka,

please provide some more details on your project setup, as it is likely that symbol resolving issues are caused by problems in the project setup (telling the editor/compiler/bundler where to find libraries).

**Comment by kiuka** [comment]
Thanks for your fast reply.

IDE: PHPStorm 2016.2.1
other relevant tools: systemjs (0.19.39), gulp (3.9.1), typescript (2.0.3)

I use Mgechev's  seed project: https://github.com/mgechev/angular-seed, after clone I did the following:

npm install ng2-page-scroll --save

In tools/config/seed.config.ts:
SYSTEM_CONFIG_DEV.paths:
      'ng2-page-scroll': 'node_modules/ng2-page-scroll/bundles/ng2-page-scroll.umd.js',

SYSTEM_BUILDER_CONFIG.packages:
      'ng2-page-scroll': {
        main: 'ng2-page-scroll.js',
        defaultExtension: 'js'
      }

**Comment by kiuka** [comment]
And pleeease merge the update from two days ago into a release, because the wrong peer dependency also causes problem:)

**Comment by Nolanus** [comment]
Instead of overriding the `seed.config.ts` (I wouldn't recommend that, as it's the base and customizations should go into `project.config.ts`) add the following line to `project.config.ts` file:

```
this.SYSTEM_CONFIG_DEV.paths['ng2-page-scroll/ng2-page-scroll'] =  'node_modules/ng2-page-scroll/bundles/ng2-page-scroll.umd';
```

Then you may import the `Ng2PageScrollModule`

```
import {Ng2PageScrollModule} from 'ng2-page-scroll/ng2-page-scroll';

...
@NgModule({
    imports: [..., Ng2PageScrollModule],
    ...
})
```

**Comment by kiuka** [comment]
You are right, the seed config should not be changed:)

It works fine after I added the second /ng2-page-scroll to the import line. Thank you very much:)
