### ISSUE TITLE
Wait for content to load from the components when changing router

### ISSUE THREAD

**Issue by stefan1st** [Nolanus/ng2-page-scroll#48]
I use ng2-page-scroll like this:

```
<a pageScroll [routerLink]="['router-one']" href="#content1">Link 1</a>
<a pageScroll [routerLink]="['router-two']" href="#content2">Link 2</a>
<a pageScroll [routerLink]="['router-three']" href="#content3">Link 3</a>
```

Works fine, exceptat that... let's say I'm on _router-one_, fragment _content1_, and I click Link2, where I have many components, that need to load their data. After routing has finished, its just goes to my fragment, which is understandable, but my data is probably not loaded yet, and will load in the next 1000ms maybe. 

So it basically, goes to that id/fragment, and than the data loads, and you are no longer seeing on your screen the section with the id/fragment that you requested for, you must manually scroll to it

How can I set like a delay to give the data a change to load, when you work across routes?

**Comment by Nolanus** [comment]
Hi @stefan1st,

your problem is that the data on the route you navigate to requires some time to load?
I guess the best way to handle this situation is using the `PageScrollService` on the target route/component to trigger the scroll animation as soon as the data is loaded (you probably get an event when this happens, e.g. the http request finished). You may pass the scroll target element to the new route as [optional route parameter](https://angular.io/docs/ts/latest/guide/router.html#!#optional-route-parameters).

**Comment by stefan1st** [comment]
Hi @Nolanus, thank you for your response.

I actually made something like this for each component: `@Output() dataLoaded: EventEmitter<boolean> = new EventEmitter<boolean>()`

My navigation component that contains the directive `pageScroll ` remained unmodified: 
`<a pageScroll [routerLink]="['router-one']" href="#content1">Link 1</a>
<a pageScroll [routerLink]="['router-two']" href="#content2">Link 2</a>
<a pageScroll [routerLink]="['router-three']" href="#content3">Link 3</a>`

My next question is how does PageScrollService injected in my main component, gets the data from the component containing the pageScroll directive, and act accordingly if all data is loaded?

**Comment by Nolanus** [comment]
Your a-tags/links do not use the `pageScroll` directive in this case:

```html
<a [routerLink]="['router-one', { scrollTo: '#content1' }]">Link 1</a>
```

In your target component you then access the _scrollTo_ value from the _activatedRoute_ and pass it into `PageScrollService`, something like:

```ts
constructor(
     private route: ActivatedRoute,
     private pageScrollService: PageScrollService,
     @Inject(DOCUMENT) private document: Document) {}

  ngOnInit() {
    this.route.params.forEach((params: Params) => {
        if (params['scrollTo']){
            let pageScrollInstance: PageScrollInstance = PageScrollInstance.simpleInstance(this.document, params['scrollTo']);
            this.pageScrollService.start(pageScrollInstance);
        }
  }
```

Please note that I just wrote this code without testing, but it should give you an idea of the solution.
