### ISSUE TITLE
Not working in Firefox or IE 11

### ISSUE THREAD

**Issue by bensgroi** [Nolanus/ng2-page-scroll#5]
The directive doesn't appear to work in Firefox or IE for me, but does in Chrome. Try the following in Chrome, then in Firefox: http://plnkr.co/edit/fMGyl0a7xyMSR8doZASO?p=preview 

(The above Plunker is really broken in IE 11, though I'm not seeing that particular error in my actual app; it simply doesn't scroll, similar to what you see here in Firefox)

I'm using RC1.

I tried verifying this with the provided example app, but I can't get it to run. It's giving me errors regarding the typings command. I'll see if I can figure out what the problem is.

**Comment by Nolanus** [comment]
Hi,
thanks for the plunker. I'm getting similar results to your observation: works fine in Chrome (50.0.2661.102) and Safari (9.1.1) but fails in Firefox (45.0.2).

Regarding the demo application: make sure you've `npm install`ed to root project before starting inside the example folder. I just added a new npm script `npm run example` to simplify that and clarified the documentation.

**Comment by Nolanus** [comment]
The issue should be fixed now. Problem was a wrong parameter name, which caused the global window.event object to be used in the "onscroll" listener. As some browser implement this [non-standard, old-IE behavior to work correctly with old websites](http://stackoverflow.com/a/16306549/2225619), it worked with some browsers.

**Comment by bensgroi** [comment]
Hm, it still seems to be not working in Firefox (46.0.1). I forked my original Plunker and just changed the ng2-page-scroll version: http://plnkr.co/edit/7mTE6FoHHqNWp5qPS6vW?p=preview

**Comment by bensgroi** [comment]
The problem seems to be due to the fact that `body.scrollTop` is non-standard and is only supported in Blink: https://dev.opera.com/articles/fixing-the-scrolltop-bug/  

Using `document.documentElement.scrollTop` in addition to `body.scrollTop` will ensure the scrolling happens in Chrome, IE, & Firefox.

I can submit a PR if you'd like.
