### ISSUE TITLE
How can I delay PageScrollService.start?

### ISSUE THREAD

**Issue by stefan1st** [Nolanus/ng2-page-scroll#52]
Can i somehow delay PageScrollService.start?

**Comment by Nolanus** [comment]
There's not built in way to delay the scroll start. However, there should be no need, as you may delay the call to `PageScrollService.start()`. Either wait for an event to be emitted by an [EventEmitter](https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html), a call to the subscriber of an observable (like [angular2 http](https://angular.io/docs/ts/latest/guide/server-communication.html)) or [`setTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout) when the scrolling should start after a given amount of time.
