### ISSUE TITLE
Remove *.ts files from src during publishing to npm

### ISSUE THREAD

**Issue by inzerceubytovani** [Nolanus/ng2-page-scroll#54]
I got this errors during transpiling: Error TS6059: File '.../node_modules/ng2-page-scroll/src/ng2-page-scroll-instance.ts' is not under 'rootDir' '../client/app/'. 'rootDir' is expected to contain all source files. ... for every ts file.

This happens where .ts files are in node_modules folder. It's possible to not include this souce files during publishing to npm?

**Comment by Nolanus** [comment]
Hello @inzerceubytovani, I'm not sure what your process looks like, but usually you configure the typescript compiler to only compile/transpile your own source files, so adding _node_modules_ folder to the exclude list may solve your problem. As the libraries usually contain transpiled versions of the typescript code there's not need for you to do so.

**Comment by inzerceubytovani** [comment]
I use exclude node_modules, but that's same problem like here: https://github.com/ocombe/ng2-translate/issues/4

**Comment by inzerceubytovani** [comment]
And also getting this error:

`..node_modules/ng2-page-scroll/ng2-page-scroll.js:1
export * from './src/ng2-page-scroll.directive';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

When I try to bundle project with browserify in gulp.

**Comment by Nolanus** [comment]
Your last error sounds like an ecma script versioning problem to me. You may find es5 umd modules in the `/bundles/`directory. All other _*.js_ files are es6.
