### ISSUE TITLE
Scroll broken when zoom <> 100%

### ISSUE THREAD

**Issue by rychoo2** [Nolanus/ng2-page-scroll#55]
Scrolling isn't working when browser zoom is different than 100%.
To reproduce, 
1) go to the demo page:
http://nolanus.github.io/ng2-page-scroll/simple
2) change browser zoom ctrl[+/-]
3) click Start
Issue observed on chrome and safari

**Comment by Nolanus** [comment]
Thanks for the bug report, I'll have a look into this.
Symptoms look similar like for #37

**Comment by rychoo2** [comment]
Thanks. Must be something with handling animation. Works fine when no animation:
PageScrollConfig.defaultDuration = 0;
