### ISSUE TITLE
PeerDependencies in 3.2.2

### ISSUE THREAD

**Issue by inzerceubytovani** [Nolanus/ng2-page-scroll#57]
You changed "rxjs": "5.0.0-beta.12" to "rxjs": "~5.0.0-rc.2" but core @angular modules wants still 5.0.0-beta.12 so I can not install version 3.2.2 now,  3.2.1 works.

**Comment by Nolanus** [comment]
Hi @inzerceubytovani,

you can install it, however a peerDependency warning will be shown, which does not stop the installation.
I'll change the peerDep to meet angular 2.1.2
