### ISSUE TITLE
Should it work with angular2 rc1?

### ISSUE THREAD

**Issue by bbottema** [Nolanus/ng2-page-scroll#6]
I think they renamed "router" to "router-deprecated" and there's a new beta router with the name "router". Using angular2 rc1, I was unable to get this to work.

Perhaps ng2-page-scroll should now import router-deprecated instead? The new one is still in beta and documentation hasn't even been published yet.

**Comment by bensgroi** [comment]
The latest version does use RC1 and the new router.

**Comment by Nolanus** [comment]
Hi bbottema,

yes, it is supposed to work with rc1 of angular2. As @bensgroi pointed out, starting with version [v1.0.0-beta.0](https://github.com/Nolanus/ng2-page-scroll/releases/tag/v1.0.0-beta.0) it's using angular2 rc1 and the new beta router. In the example app you may find a working example.

The basic usage of the new router is comparable to router-deprecated. As the name clearly states it is deprecated and shouldn't be used in a project any longer, when updating to rc1 you should update the router as well. I have no plans of providing a version that is angular2 rc1 conform but uses the deprecated router.

**Comment by morocarlo** [comment]
if you use the old router system change
`import {Router} from '@angular/router';`
to
`import {Router} from '@angular/router-deprecated';`
