### ISSUE TITLE
lock to only angular major to make it easier to upgrade to new versions of the lib

### ISSUE THREAD

**Issue by sfabriece** [Nolanus/ng2-page-scroll#62]
since angular won't introduce breaking changes until version 3, wouldn't it be ok to lock the angular dependecies to something like: `2.x.x`?

**Comment by Nolanus** [comment]
Theoretically that should be fine, however, even minor changes may alter the behavior, resulting in problems with the software. Thus I favor more strict constraints for dependencies.
I've planned to integrate [greenkeeper](https://greenkeeper.io/) to update the dependency versions more easily and get notified when any update causes problems. This should allow me to soon release a new version whenever a new angular version is released.

**Comment by sfabriece** [comment]
Sounds good, thanks 😄
