### ISSUE TITLE
Can't scroll to top of page (above router-outlet)

### ISSUE THREAD

**Issue by fergusg** [Nolanus/ng2-page-scroll#63]
I have a page like:

```html
<body>
  <my-app>
    <div id="top">Navigation</div>
    <some-content></some-content>
    <router-outlet></router-outlet>
    <a pageScroll href="#top">TOP</a>
  </my-app>
</body>
```

but the `pageScroll` never goes past the top of the `router-outlet`.  From the docs, it may be the intention that `pageScroll` is **just** for scrolling within routes.  Am I right?

Adjusting `pageScrollOffset` (e.g., to `-(height of top content)`) doesn't seem to help.

This is with 4.0.0-beta.1

**Comment by Nolanus** [comment]
Scrolling should work outside of the routes as well. Just tried it in a basic example locally and it works as expected (will include that in the demo shortly).
Can you double check that you're using the correct "scrolling view" (https://github.com/Nolanus/ng2-page-scroll#using-the-right-scrolling-view) and maybe create a plunkr reproducing the problem?
Thanks!

**Comment by fergusg** [comment]
Yes, using an explicit `PageScrollInstance` fixed it.

Thanks for your help
