### ISSUE TITLE
How to use with components

### ISSUE THREAD

**Issue by rodneyjoyce** [Nolanus/ng2-page-scroll#67]
Hi,

I've been following your Demo example app and trying to achieve the following: I want a "Go to Top" link in my footer component that will scroll up to the top of the CURRENT page.

When I put it in the same component - e.g:

```
<div id="top">
    <app-topnav></app-topnav>

    <router-outlet></router-outlet>
    <app-spinner></app-spinner>

    <app-footer></app-footer>
    <a pageScroll href="#top">Back to Top</a>
</div>
```

Then it works (ie. it scrolls nicely to the top on any page). As soon as I move the exact same code    
` <a pageScroll href="#top">Back to Top</a>`

into my footer.component then it stops working. When I am on the home page it jumps to the top with no animation and if I am on a different Route/View then it reloads the SPA with http://localhost:4200/#top

I have similar issues with the TopNav and trying to jump to a certain anchor on a component on sub page.

**Comment by Nolanus** [comment]
Hi @rodneyjoyce, did you try the "solution" that helped in #63?
