### ISSUE TITLE
Navigate to an anchor in some other page.

### ISSUE THREAD

**Issue by gowthamrodda** [Nolanus/ng2-page-scroll#68]
I understood how to navigate to an anchor inside a page. How about navigating to an anchor in a different page?

**Comment by rodneyjoyce** [comment]
I think this is similar to my question - https://github.com/Nolanus/ng2-page-scroll/issues/67

I could not get it working

**Comment by Nolanus** [comment]
Hi @gowthamrodda, please check out the example section for the directive in the readme: https://github.com/Nolanus/ng2-page-scroll#example-1

It's basically just applying the pageScroll directive and routerLink to the same DOM element.

**Comment by well-made** [comment]
I was looking for this exact same feature, your example-1 worked like a charm.

Is it also possible to trigger an event at the subscription before the scroll, I have a bootstrap `collapse` element that needs to be opened first.

**Comment by gowthamrodda** [comment]
Hy, This worked for me.
  constructor(private router: Router,
              private SharedService: AppSharedService,
              private pageScrollService: PageScrollService,
              @Inject(DOCUMENT) private document: any,
              private elementRef: ElementRef) {

    let pageScrollInstance: PageScrollInstance = PageScrollInstance.simpleInstance(this.document, '#app-resources');
    this.pageScrollService.start(pageScrollInstance);

  }


with the above code on route change , scrolling to top or mentioned anchor. but this is not working in safari of iphone. ? any thoughts?

**Comment by TJ2001** [comment]
I'm following the example: `<a pageScroll [routerLink]="['Home']" href="#myanchor">Go there</a>` with `<a pageScroll [routerLink]="['home']" href="#contact">Contact</a> ...  <div id="contact">
  <app-contact></app-contact>
</div>`

The go to different route then scroll down functionality  works perfectly. Love it, but when it is already on the home route it won't scroll down. It doesn't do anything if it's already on the home route. Am I missing something here? Thoughts?

**Comment by TJ2001** [comment]
I follow the example 
```sh
<a pageScroll [routerLink]="['Home']" href="#myanchor">Go there</a>
```
with
```sh
<a pageScroll [routerLink]="['home']" href="#contact">Contact</a> ... <div id="contact">
  <app-contact></app-contact>
</div>

```

The go to different route then scroll down functionality works perfectly. Love it, but when it is already on the home route it won't scroll down. It doesn't do anything if it's already on the home route. Am I missing something here? Thoughts?

**Comment by TJ2001** [comment]
I got it working using 
```sh
<a pageScroll routerLink="/home" routerLinkActive="active" href="#contact"><a pageScroll href="#contact">Contact1</a></a>
```
I know it's sub-optimal. But, it works... If anyone has any thoughts why the regular way is not working properly, i'm open to suggestions.

**Comment by xmlking** [comment]
I have same issue as @TJ2001 stated.  workaround seems  like double subscribing and cause some jiggling  :(

**Comment by xmlking** [comment]
Here  is little better solution:
The trick is to add `fragment="xyz"`.  Since @Nolanus expecting `href="#xyz"` , we have add both until @Nolanus fix it.

```html
    <div class="collapse navbar-collapse" [ngbCollapse]="isCollapsed">

      <div class="navbar-nav mr-auto">
        <!-- FIXME: https://github.com/angular/angular/issues/13205 -->
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" routerLink="/home" fragment="one" href="#one">Intro</a>
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" routerLink="/home" fragment="two" href="#two">Highlights</a>
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" routerLink="/home" fragment="three" href="#three">Gallery</a>
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" routerLink="/home" fragment="four" href="#four">Features</a>
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" routerLink="/home" fragment="last" href="#last">Contact</a>
      </div>

      <div class="navbar-nav">
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" routerLink="/home/blog" i18n>Blog</a>
        <a pageScroll class="nav-item nav-link" routerLinkActive="active" routerLink="/home/about" i18n>About</a>
      </div>

    </div>
```
