### ISSUE TITLE
window scroll from bottom to top on clicking from first anchor tag to second.

### ISSUE THREAD

**Issue by PradeepGill** [Nolanus/ng2-page-scroll#70]
I have a div tag in that, i have an anchortag with all href="#target". Like this:- 
`<div><ul><li><a href="#target1">Target 1</a><a href="#target2">Target 2</a><a href="#target3">Target 3</a><a href="#target4">Target 4</a></li></ul></div><div id="target1">Content</div><div id="target2">Content</div><div id="target3">Content</div><div id="target4">Content</div>`

Steps1:- Click on Target 2 (Works fine Window scroll from top to bottom)
Steps2:- Click on Target 3 (Works fine Window scroll from top to bottom)
Steps3:- Click on Target 2 (Works fine Window scroll from top to bottom)
Steps4:- Click on Target 1 (Works fine Window scroll from top to bottom)
Steps5:- Click on Target 2 (**Window scroll from bottom to top**)

Please provide the solution for the same.
What am doing wrong.

**Comment by Nolanus** [comment]
Given your code nothing is wrong. Could you create a plnkr reproducing your problem?

**Comment by PradeepGill** [comment]
Yes sure, Please find link below
[https://plnkr.co/edit/c2GqkS?p=preview](https://plnkr.co/edit/c2GqkS?p=preview)

I am not able to add node_modules folder so is will not work as expected but you can go through the code in app.ts

   =========                       OR                     ===============

In your demo folder


In file name **app.component.ts**

`import {Component, ElementRef, Inject} from '@angular/core';
import {PageScrollService, PageScrollInstance} from 'ng2-page-scroll';
import {DOCUMENT} from "@angular/platform-browser";
import {Router, NavigationEnd} from "@angular/router";
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {

    constructor(private router: Router) {
        router.events.subscribe((event) => {
            // see also
            if (event instanceof NavigationEnd) {
                this.links.forEach((link, index) => {
                    if (link.route[0] === event.url) {
                        this.currentTabIndex = index;
                    }
                });
            }
        });
    }

    public currentTabIndex: number = 0;

    public links = [
        {
            route: ['/'],
            name: 'Home'
        }];

    public tabChange(event: any) {
        // Select the correct route for that tab
        let routeObj = this.links[event.index];
        if (routeObj && routeObj.route) {
            this.router.navigate(routeObj.route);
        }
    }

}
`

In file name **app.component.html**
continue to plunker for this file.

Please let me know any thing required from my side.

**Comment by StanFaas** [comment]
Did you manage to fix this one? We have the same problem. Let me know, thanks.

**Comment by Nolanus** [comment]
This issue has been fixed 4.0.0-beta.7 release as for #125
