### ISSUE TITLE
Instance of PageScrollService already exists when using TestingModule

### ISSUE THREAD

**Issue by JFMueller** [Nolanus/ng2-page-scroll#74]
`@NgModule({
    imports: [Ng2PageScrollModule.forRoot()]
})
export class AppModule`

We need Ng2PageScroll directives to achieve the following:
`<a pageScroll href="#ref1">ref1</a>
<a pageScroll href="#ref2">ref2</a>`

So we import it into the module that wants to to declare a component that uses Ng2PageScroll.
`@NgModule({
    imports: [Ng2PageScrollModule]
})
export class ModuleUsesNg2PageScroll`

All this works fine, but the moment we run unittests the following warning appears:
_An instance of PageScrollService already exists, usually including one provider should be enough, so double check._

It appears the moment, the first beforeEach() finishes and the second beforeEach() starts:
` beforeEach(done => {
TestBed.configureTestingModule({
            imports: [ModuleUsesNg2PageScroll, ModuleUsesNg2PageScroll.forRoot()]
        }).compileComponents().then(() => {
            fixtureComponent = TestBed.createComponent(ComponentWithScrolling);
done();
        });
    });`

Some logs:
`LOG: 'Before Each 0'`
`LOG: 'PageScrollService.instanceCounter'`
`LOG: 1`
`LOG: 'Before Each 1'`
`WARN: 'An instance of PageScrollService already exists, usually including one provider should be enough, so double check.'`
`LOG: 'PageScrollService.instanceCounter'`
`LOG: 2`
`LOG: 'Before Each 2'`
`WARN: 'An instance of PageScrollService already exists, usually including one provider should be enough, so double check.'`
`LOG: 'PageScrollService.instanceCounter'`
`LOG: 3`

The moment I remove Ng2PageScrollModule from the imports of ModuleUsesNg2PageScroll all works fine for testing, but of course the application can not use the **pageScroll** directive anymore and does not scroll correctly. I'm not sure if this behaviour is intented and would be happy about further informations.

**Comment by Nolanus** [comment]
The warning is displayed if a static instance counter of the PageScrollService detects that multiple instances are constructed (see https://github.com/Nolanus/ng2-page-scroll/blob/1101e043a476b7fca13de4f02c54131d2600fd42/src/ng2-page-scroll.service.ts#L201). Scroll animations started by two different instances of the PageScrollService are not aware of each other. This prohibits that a later started scroll animation first stops the previously started one before starting its own animation.
The warning is in place to point out this possibly expensive situation producing unintended behavior.  I assume in your testing situation the code is loaded once and multiple angular2 applications are created, each one of course constructing its own PageScrollService instance. Thus it should be no problem.
