### ISSUE TITLE
 Lazy Routes seems not working

### ISSUE THREAD

**Issue by masaanli** [Nolanus/ng2-page-scroll#75]
Having lazy routes and trying to make it work there.

Can not get it to work. Nothing happens?

I added it into my App Module ;)

Just made in my comonent on a button click and added a <p id="block-uploads">test</p>
```
let pageScrollInstance: PageScrollInstance = PageScrollInstance.simpleInstance(this.document, '#block-uploads');
      this.pageScrollService.start(pageScrollInstance);
```

**Comment by masaanli** [comment]
Closed. Problem solved, was my CSS (Flexbox which was breaking it)

**Comment by maku** [comment]
@masaanli Can you explain what the problem was for you (I am using angular/material2 and flex-layout). I am not able to get ng2-page-scroll working ....
