### ISSUE TITLE
Section detection

### ISSUE THREAD

**Issue by TeodorKolev** [Nolanus/ng2-page-scroll#78]
Needed detection of current section is scrolled to set menu item class - current.

**Comment by Nolanus** [comment]
I think you're looking for something like "scrollspy" or "bootstrap affix". There's a [PR waiting for ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap/pull/339) or you can check out [ng2-scrollspy](https://github.com/jonnybgod/ng2-scrollspy)
