### ISSUE TITLE
Is it possible to different route using service?

### ISSUE THREAD

**Issue by olaf89** [Nolanus/ng2-page-scroll#79]
I was trying to navigate to element in different route using service, but i couldnt find information how to do it, is it possible?  are there any limitations to service api compared to directive?

**Comment by Nolanus** [comment]
No, that is not possible. The handling of the route change detection is only available to the directive.

You can trigger the scrolling via the scroll service from inside the onInit() method or similar on your new controller to get the desired behavior.
