### ISSUE TITLE
Allow passing an object as options to advancedInstance

### ISSUE THREAD

**Issue by Maistho** [Nolanus/ng2-page-scroll#81]
`advancedInstance` has too many options to put them all as arguments to the function. It's error prone, and using an options object instead would be better.

Instead of using the following pattern:
```typescript
PageScrollInstance.advancedInstance(this.document, '#myId', null, null, true, 10, true, null, 300);
```

I should (also) be able to write:
```typescript
PageScrollInstance.advancedInstance({
    document: this.document,
    scrollTarget: '#myId',
    isVerticalScrolling: true,
    pageScrollOffset: 10,
    pageScrollInterruptible: true,
    pageScrollDuration: 300,
});
```

It makes users less likely to make errors, since they no longer have to remember the order of the options. It is also easier to implement new options moving forward.

Would you be interested in a pull request with these changes?

**Comment by Nolanus** [comment]
Very good suggestion, no idea why I didn't come up with this initially.
PR would be awesome
