### ISSUE TITLE
Is it possible to scroll back on pressing Back button?

### ISSUE THREAD

**Issue by yuriykuzin** [Nolanus/ng2-page-scroll#83]
When I use this directive to scroll down on pressing the link and then I press browser Back button, I'm navigated to a previous route. Is it possible to scroll smoothly back to initial position in this case?
Thanks in advance!

**Comment by Nolanus** [comment]
There's nothing like a back stack of scroll animations that have been performed. You can do that manually in your application. You could [add a new history state](https://angular.io/docs/ts/latest/api/common/index/PlatformLocation-class.html#!#pushState-anchor) when a scroll animation has finished and listen for back button presses using the [onPopState event](http://stackoverflow.com/a/40300969).

**Comment by yuriykuzin** [comment]
Okay, thank you. I've solved it writing my own directive with these two steps.
