### ISSUE TITLE
Cannot change target after app is loaded

### ISSUE THREAD

**Issue by olaf89** [Nolanus/ng2-page-scroll#84]
In newest version im trying to use directive to navigate between sections on page. My sections are computed dynamically It looks like after initial bind to some id, it cannot be changed later. While debugging i can see 
"_scrollTarget" has incorrect value which is the initial one, instead of current one.

**Comment by Nolanus** [comment]
That's correct. Once the scroll animation has been triggered, the values are read from the angular system and stored in the _pageScrollInstance_. I'll put it on the ToDo list to test whether regenerating the pageScrollInstance every time has any downsides.

In the meantime you can either use the _PageScrollService_ directly or consider updating your app to hide/show the links based in your dynamic content instead of changing the _href_ link target (and thus the elements behavior).

**Comment by olaf89** [comment]
Links are provided from backend service,  based on user roles, so i dont know what will be the target, so cannot hide/show. I was using scrolling service and worked perfectly, but now i have requirement to navigate also between pages thats why i was sure directive is a better way to do that.
Do you maybe have an suggestion how can i  "quickfix it" to recreate this component so the pageScrollInstance is regenerated? And as for proper solution I understand that its performance reason why instance is created once instead of each time, could it be configurable to recreate instance each time? like dynamic flag  I could maybe try to create PR doesnt seem that difficult. It could work for people with similar needs.

**Comment by Nolanus** [comment]
Check out this line: https://github.com/Nolanus/ng2-page-scroll/blob/master/src/ng2-page-scroll.directive.ts#L62
Removing that if-check and always creating a new instance using the factory method _PageScrollInstance.advancedInstance_ should to the trick.

**Comment by olaf89** [comment]
Looks promising, but i would like to keep using this library. And from what i understand you are not sure if that's the way to go forward. So what do you think about input like dynamicTarget and then
 if (PageScrollUtilService.isUndefinedOrNull(this.pageScrollInstance) || this.dynamicTarget) ...

**Comment by Nolanus** [comment]
That's definitely how a solution could look like, but you asked for a quickfix. Recreation of the directive may be triggered by removing it from the dom, e.g. by placing an ngIf at the parent node.
