### ISSUE TITLE
AOT problems: ERROR in Error encountered resolving symbol values statically. Could not resolve type Document

### ISSUE THREAD

**Issue by stevermeister** [Nolanus/ng2-page-scroll#85]
for 

```
 @Inject(DOCUMENT) private _document: Document
```

**Comment by Nolanus** [comment]
Hi,
replacing `Document` with `any` resolves the problem (refer to https://github.com/Nolanus/ng2-page-scroll/issues/35#issuecomment-250939092).

I'll update the documentation

**Comment by stevermeister** [comment]
unfortunately(or fortunately) we don't except "any" in our project :/

**Comment by Nolanus** [comment]
Follow up this issue https://github.com/angular/angular/issues/12631 and let's hope they figure out a fix soon.
