### ISSUE TITLE
Feature Request: Mousewheel exececutes pageScroll

### ISSUE THREAD

**Issue by csawtelle** [Nolanus/ng2-page-scroll#87]
It would be really nice if you could bind the page scroll even to a mousewheel click. Currently you have to click an element to move to the anchor, such as this:

```
<div class="hover_bar">
      <a pageScroll href="#scroll_anchor" class="more" #hover_trigger></a>
      <i class="fa fa-arrow-down" aria-hidden="true" (mouseover)='hover_trigger.click()'></i>
</div>
```
It would be really nice if you could do something like 

`(mousewheeldown)="hover_trigger"`

so that a scroll down on the mouse would take you to the specified anchor, equivalently mousewheelup could specify a separate anchor.

**Comment by Nolanus** [comment]
Hi,

thanks for your suggestion, but I assume that use case is quite specific and adding it to the the "core" ng2-page-scroll just increases the libraries complexity with a few people using it.

Anyhow, this could easily be implemented by binding to the window scroll event and triggering the scroll animation using the PageScrollService. 

```
@Component({
// Your component stuff here
})
export class MyComponent {
 constructor(@Inject(DOCUMENT) private document: Document, private pageScrollService: PageScrollService) { }

  @HostListener("window:scroll", ['$event'])
  onWindowScroll(event) {
     // Read data from the scroll event and create a pageScrollInstance
     let pageScrollInstance: PageScrollInstance = null; // TODO
     this.pageScrollService.start(pageScrollInstance);
  }
}
```
