### ISSUE TITLE
PageScroll slows the page down a lot

### ISSUE THREAD

**Issue by bbottema** [Nolanus/ng2-page-scroll#9]
When in use, the performance of the page takes a huge hit. Even normal scrolling using the mouse-wheel is very laggy. Increasing `PageScrollConfig._interval` doesn't seem to make a difference.

The page becomes instantly super smooth again as soon as I don't include the `PageScroll` directive.

**Comment by Nolanus** [comment]
Thanks for the research. At the moment for every anchor using pageScroll the listeners are registered. This adds up when there are multiple links on the page.
I'll rethink the approach and at least make the "interference detection" optional.

**Comment by bbottema** [comment]
Ah yes, I have 13 anchors, so that would explain it.

**Comment by Nolanus** [comment]
Hi, the performance should be better now, as event listener only get attached for the time the page scroll animation takes place (74080862547bba2ae004f017c13626aa1b9f7840).
Appreciating your feedback whether it's now better in your project.
