### ISSUE TITLE
Not able to scroll to nested divs

### ISSUE THREAD

**Issue by finleysg** [Nolanus/ng2-page-scroll#91]
This is the markup of the containing div:
```
<div #scrollContainer class="scrollable">
    <div class="card" *ngFor="let table of tables" id="{{'course-' + table.courseSetupId}}">
        <div class="card-body card-padding">
            <div class="row" *ngFor="let row of table.rows" id="{{'hole-' + row.holeId}}">
                <div class="col-sm-1">
                    <div class="registration-hole">
                        <span *ngIf="row.name">{{ row.name + ' ' + table.courseName }}</span>
                    </div>
                </div>
                <div class="col-sm-2" *ngFor="let slot of row.slots">
                    <div id="{{generateId(slot)}}" class="row registration-slot" [class.found]="slot.selected">
                        <div class="col-sm-12 member-name">
                            <span>{{slot.memberName}}</span>
                        </div>
                        <div class="col-sm-3 is-paid text-center" [class.selected]="slot.registration.isGrossSkinsFeePaid">GS</div>
                        <div class="col-sm-3 is-paid text-center" [class.selected]="slot.registration.isNetSkinsFeePaid">NS</div>
                        <div class="col-sm-3 is-paid text-center" [class.selected]="slot.registration.isGreensFeePaid">GF</div>
                        <div class="col-sm-3 is-paid text-center" [class.selected]="slot.registration.isCartFeePaid">CT</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

I have created ids at three levels: card (3 get rendered), row (51 get rendered), and column (5 per row). When I do a scroll (code below) to the card level, the behavior is mostly as expected, although the distance is about 100 pixels too far.

When I try to scroll to a row id, the scrolling stops after about two rows (100 pixels or so). When I try to scroll to a column id, the scrolling stops after just a few pixels.

A scroll is triggered by a search for a member name within a "slot" (column div):

```
    findMember($event: TypeaheadMatch) {
        // Change the styling to highlight the member and scroll into view
        let anchor: string = 'none';
        this.tables.forEach((table: EventSignupTable) => {
            table.rows.forEach((row: RegistrationRow) => {
                row.slots.forEach((slot: RegistrationSlot) => {
                    slot.selected = (slot.memberId === $event.item.id);
                    if (slot.selected) {
                        // anchor = `#course-${slot.registration.courseSetupId}`;
                        anchor = `#hole-${slot.row.holeId}`;
                        // anchor = `#member-${slot.memberId}`;
                    }
                });
            });
        });
        if (anchor !== 'none') {
            let pageScrollInstance: PageScrollInstance = PageScrollInstance.simpleInlineInstance(this.document, anchor, this.container.nativeElement);
            this.pageScrollService.start(pageScrollInstance);
        }
    }
```

Ideally I'd like the row to be the element I target (hole-N), but scrolling to the card element is the only thing close to working.

Am I misunderstanding something, or maybe I'm asking too much from the library?

Thank you for your fine work.

**Comment by Nolanus** [comment]
Hi,

please check the plunkr I quickly created with your given code: https://plnkr.co/edit/WIP8D8?p=preview
A css change was required to properly get the offset position of the scrollTarget elements. The scroll container needs to be first element in the vie hierarchy of the scrollTarget element with `position: relative`. In your example every card has `position: relative`, thus the library retrieves the scrollTarget element's position relative to that card instead of the scroll container.

Unfortunately I'm not sure whether that breaks anything of your layout.

**Comment by finleysg** [comment]
That makes sense. Using static positioning in this case works ok, so I can move forward. Thank you!
