### ISSUE TITLE
Use with angular/cli and lazily loaded modules

### ISSUE THREAD

**Issue by achimha** [Nolanus/ng2-page-scroll#96]
The documented approach of adding

```
Ng2PageScrollModule.forRoot()
```

to the imports of the root module does not work in case of lazily loaded modules via the angular router and angular/cli's webpack. One has to import the scroll module in each lazily loaded module.

Should this be improved? Instead of doing `.forRoot()` everywhere, should there be a a `forRoot()` and a `forChild()` like for the angular router?

At least the docs should be updated I believe.

**Comment by picosam** [comment]
Hello, if I currently want to use this *only* in a lazy loaded module as described above, should I simply use `Ng2PageScrollModule.forRoot()` there instead of in the root module? Thanks!

**Comment by Nolanus** [comment]
`Ng2PageScrollModule.forRoot()` should only be used once per application at the highest injector. This in most cases is the root injector (often called `AppModule`).

When using lazy loaded modules one should not use `.forRoot()` again, as pointed out by the comments and angular documentation. It will results in multiple instances of the `PageScrollService` which is also logged into the console (_Warning: An instance of PageScrollService already exists, usually including one provider should be enough, so double check._)

To inject the PageScroll directive into lazy loaded modules one can use the Ng2PageScrollModule directly:

    imports: [..., Ng2PageScrollModule],

Example plunkr: https://plnkr.co/edit/LK97DhyhWbSdxidICiFN?p=preview

In case the PageScroll functionality is only required in a lazy loaded module, injecting the `ModuleWithProviders` return from `Ng2PageScrollModule.forRoot()` in the lazy loaded module should do it. As the while feature is only used and required in there, it can be considered the logical root of it, although the the lazy loaded module isn't the root of the while application. Anyhow I agree with @achimha and will add a `forChild()` method to meet conventions suggested by the angular team.

Example plunkr: https://plnkr.co/edit/0PHBwjNzEB4dxhBC8bnj?p=preview

**Comment by achimha** [comment]
Thanks for picking this up. However, the `forRoot`/`forChild` method is cumbersome and there is a more elegant solution.

Have a look at this component which is also a singleton service.

https://github.com/xmaestro/angular2-recaptcha/blob/master/lib/captcha.service.ts#L47

```
/* singleton pattern taken from https://github.com/angular/angular/issues/13854 */
export function RECAPTCHA_SERVICE_PROVIDER_FACTORY(ngZone: NgZone, parentDispatcher: ReCaptchaService) {
    return parentDispatcher || new ReCaptchaService(ngZone);
}

export const RECAPTCHA_SERVICE_PROVIDER = {
    provide: ReCaptchaService,
    deps: [NgZone, [new Optional(), new SkipSelf(), ReCaptchaService]],
    useFactory: RECAPTCHA_SERVICE_PROVIDER_FACTORY
};
```

**Comment by achimha** [comment]
Any chance that the `forRoot / forChild` will be replaced by auto-detection of the singleton?

I don't think your workaround mentioned above works for applications where several lazily loaded modules but only lazily loaded modules use the service.

**Comment by Nolanus** [comment]
Hi @achimha,
unfortunately I'm very short on time at the moment, so it might take even longer. But feel free to create a PR for that I can review and release. Thanks
