### ISSUE TITLE
Usage in combination with ngFor and item index changes

### ISSUE THREAD

**Issue by cmddavid** [Nolanus/ng2-page-scroll#97]
I'm trying to use this package in combination with a ngFor loop(inside ng2 dragula), this works in basic usage. But when the index of a item changes the scrolling doesn't scroll to the correct element anymore. So for example: Item with index 7 gets swapped with item with index 1, now the new index 1 still scrolls to index 7. It should be index 1.

Here are the two code snippets:

```
<span [dragula]='"bag-one"' [dragulaModel]="elements">
    <app-side-elem *ngFor="let item of elements; let i = index;" pageScroll [href]="'#item_'+i"></app-side-elem>
</span>
```

```
<div class="col s12" *ngFor="let item of elements; let i = index;" [id]="'item_'+i">
    <!-- SOME HTML HERE -->
</div>
```

According to Firefox Developer tools the ID of the target DIV gets updated correctly, and the same goes for the pageScroll element. Anyone got ideas?

**Comment by Nolanus** [comment]
Sounds like an issue related to #84. I'm afraid there's no proper workaround for that and you have to wait till I find time to add the linked enhancement.

**Comment by cmddavid** [comment]
@Nolanus Thanks for the quick reply, i will try to think of a workaround myself in the meantime. The linked issue has some useful info that could possibly help.

**Comment by Nolanus** [comment]
Should be fixed with the latest release

**Comment by cmddavid** [comment]
Thank you for the quick fix Nolanus, i'm going to test it tonight :-)

**Comment by cmddavid** [comment]
@Nolanus, it is indeed fixed! Thanks a lot.
