### ISSUE TITLE
Activate pageScroll link when manually scrolling to anchor

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [Nolanus/ng2-page-scroll#99]
hi, wondering if it is possible to make a link active that uses the pageScroll directive whenever the user manually scrolls to an anchor. 

I'm using material2 buttons:

```
<md-toolbar color="primary" class="dk-toolbar" >
    <a md-button 
        pageScroll 
        [routerLink]="['/mypage']" 
        href="#myanchor" 
        routerLinkActive="active">MY BUTTON</a>
</md-toolbar>
```

I'd like to highlight the button not only when the user clicks on it, but also when the user manually reaches the /mypage#myanchor area.

**Comment by Nolanus** [comment]
Hi,

please refer to #78 or #12 regarding that question.
